name: CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  pest:
    name: Tests (Pest) L${{ matrix.laravel }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        laravel: [8, 9, 10, 11]
        include:
          - laravel: 10.*
            testbench: 8.*
            carbon: ^2.63
          - laravel: 11.*
            testbench: 9.*
            carbon: ^2.72.2
        exclude:
          - laravel: 11.*
            php: 8.1
    steps:
    - uses: actions/checkout@v2
    - name: Install composer dependencies
      run: composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "nesbot/carbon:${{ matrix.carbon }}" --no-interaction --no-update
    - name: Run tests
      run: vendor/bin/pest

  phpstan:
    name: Static analysis (PHPStan)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install composer dependencies
      run: composer install
    - name: Run phpstan
      run: vendor/bin/phpstan analyse

  php-cs-fixer:
    name: Code style (php-cs-fixer)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install php-cs-fixer
        run: composer global require friendsofphp/php-cs-fixer
      - name: Run php-cs-fixer
        run: $HOME/.composer/vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php
      - name: Commit changes from php-cs-fixer
        uses: EndBug/add-and-commit@v5
        with:
          author_name: "PHP CS Fixer"
          author_email: "phpcsfixer@example.com"
          message: Fix code style (php-cs-fixer)
